version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    assignees:
      - "NoDocCat"
    reviewers:
      - "NoDocCat"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    assignees:
      - "NoDocCat"
    reviewers:
      - "NoDocCat"
