name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  code-check:
    name: Code check
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Cache depend
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install depend
        run: yarn install

      - name: Run code lint
        run: yarn lint

      - name: Run code test
        run: yarn test

      - name: Run test compile
        run: yarn build

      - name: Upload test coverage to codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report
