name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  code-check:
    name: Code check
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Get yarn cache path
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache depend
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install depend
        run: yarn install

      - name: Run code lint
        run: yarn run lint

      - name: Run code test
        run: yarn run test

      - name: Run test compile
        run: yarn run build

      - name: Upload test coverage to codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report
